# Generated by Django 4.2.2 on 2023-07-02 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={"ordering": ["-order"]},
        ),
    ]
