# Generated by Django 4.2.2 on 2023-07-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0002_alter_achievement_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="aggregate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
