from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.Base, name='base'),
    path('home/', views.Home, name='home'),    
    path('write-feedback/', views.Feedback, name='feedback'),
    path('donate/', views.Donate, name='donate'),
    path('users/<str:username>/profile/', views.UserProfile, name='profile'),
    path('users/<str:username>/profile/posts/', views.user_posts, name='user-posts'),
    path('users/<str:username>/profile/questions/', views.user_questions, name='user-questions'),
    path('users/<str:username>/profile/answers/', views.user_answers, name='user-answers'),
    path('users/<str:username>/profile/liked-posts/', views.user_liked_posts, name='user-liked-posts'),
    path('phases/forum/<str:forum_slug>/', views.Forum_Display, name='forum'),
    path('phases/forum/<str:forum_slug>/direct_load/', views.Forum_Display, name='forum_direct_load'),
    path('contact/', views.contact, name='contact'),
    path('get_phase_options/', views.get_phase_options, name='get_phase_options'),
    path('post_options/<str:post_id>/', views.post_options, name='post_options'),
    path('post_comment_options/<str:post_comment_id>/', views.post_comment_options, name='post_comment_options'),
    path('answer_comment_options/<str:answer_comment_id>/', views.answer_comment_options, name='answer_comment_options'),
    path('article_comment_options/<str:article_comment_id>/', views.article_comment_options, name='article_comment_options'),
    path('book_review_options/<str:book_review_id>/', views.book_review_options, name='book_review_options'),
    path('answer_comment_options/<str:answer_comment_id>/', views.answer_comment_options, name='answer_comment_options'),
    path('article_comment_options/<str:article_comment_id>/', views.article_comment_options, name='article_comment_options'),
    path('book_review_options/<str:book_review_id>/', views.book_review_options, name='book_review_options'),
    path('question_options/<str:question_id>/', views.question_options, name='question_options'),
    path('answer_options/<str:answer_id>/', views.answer_options, name='answer_options'),
    path('follow_user/<str:username>/', views.follow_profile, name='follow_profile'),
    path('block_user/<str:username>/', views.block_profile, name='block_profile'),
    path('user-logout/', views.User_logout, name='user_logout'),
    path('search/<str:tabname>/', views.SearchView, name='search'),
    path('user/settings/', views.open_settings, name='open_settings'),
    path('user/settings/change_password', views.change_password, name='change_password'),
    path('user/settings/edit_profile', views.edit_profile, name='edit_profile'),
    path('share_post/<int:post_id>/', views.share_post, name='share_post'),
    path('share_article/<int:article_id>/', views.share_article, name='share_article'),
    path('share_question/<int:question_id>/', views.share_question, name='share_question'),
    path('share_answer/<int:answer_id>/', views.share_answer, name='share_answer'),
    path('share_website/', views.share_website, name='share_website'),
    path('users/<str:username>/profile/direct_load/', views.UserProfile, name='profile_direct'),
    path('users/<str:username>/profile/posts/direct_load/', views.user_posts_direct, name='user-posts_direct'),
    path('users/<str:username>/profile/liked-posts/direct_load/', views.user_liked_posts_direct, name='user-liked-posts_direct'),
    path('users/<str:username>/profile/questions/direct_load/', views.user_questions_direct, name='user-questions_direct'),
    path('users/<str:username>/profile/answers/direct_load/', views.user_answers_direct, name='user-answers_direct'),
    path('newsletter_subscription/subscribe/', views.newsletter_subscribe, name='newsletter_subscription'),
]