# Generated by Django 4.2.2 on 2023-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_forum_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="PostImages/"),
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="QuestionImages/"),
        ),
    ]
