# Generated by Django 4.2.2 on 2023-07-16 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0003_answer_image_question_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="downvoted_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="downvoted_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="upvoted_by",
            field=models.ManyToManyField(
                blank=True, related_name="upvoted_answers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="downvoted_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="downvoted_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="upvoted_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvoted_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
