# Generated by Django 4.2.2 on 2023-07-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0005_answercomment_answercommentlike"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="content",
        ),
        migrations.RemoveField(
            model_name="question",
            name="likes",
        ),
        migrations.AddField(
            model_name="answer",
            name="aggregate",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="aggregate",
            field=models.IntegerField(default=0),
        ),
    ]
