# Generated by Django 4.2.2 on 2023-08-09 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0006_remove_question_content_remove_question_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="admirers",
            field=models.ManyToManyField(
                blank=True, related_name="answer_admirers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
