# Generated by Django 4.2.2 on 2023-08-09 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0007_answer_admirers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="aggregate",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="downvoted_by",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="upvoted_by",
        ),
        migrations.RemoveField(
            model_name="question",
            name="aggregate",
        ),
        migrations.RemoveField(
            model_name="question",
            name="downvoted_by",
        ),
        migrations.RemoveField(
            model_name="question",
            name="upvoted_by",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="downvotes",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="upvotes",
        ),
        migrations.RemoveField(
            model_name="question",
            name="downvotes",
        ),
        migrations.RemoveField(
            model_name="question",
            name="upvotes",
        ),
        migrations.AddField(
            model_name="answer",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="downvoted_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True, related_name="upvoted_answers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="downvoted_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="upvoted_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
