# Generated by Django 4.2.2 on 2023-08-09 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forum", "0008_remove_answer_aggregate_remove_answer_downvoted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="answer_followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
