# Generated by Django 4.2.2 on 2023-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0010_answer_anonymous_question_anonymous_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="AnswerImages/"),
        ),
        migrations.AlterField(
            model_name="forum",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ForumImages/"),
        ),
    ]
