from django.urls import path
from . import views

urlpatterns = [
    path('post/<int:post_id>/', views.Post_Details, name='post'),
    path('post/<int:post_id>/comments/', views.post_comments, name='post_comments'),
    path('book/<int:book_id>/', views.Book_Details, name='book'),
    path('book/<int:book_id>/reviews/', views.book_reviews, name='book_reviews'),
    path('article/<int:article_id>/', views.Article_Details, name='article'),
    path('article/<int:article_id>/comments/', views.article_comments, name='article_comments'),
    path('follow/', views.follow_social_platform, name='follow_social_platform'),
    path('question/<int:question_id>/', views.Question_Details, name='question'),
    path('answer/<int:answer_id>/', views.Answer_Details, name='answer'),
    path('answer/<int:answer_id>/comments/', views.answer_comments, name='answer_comments'),
    path('create-post/', views.create_post, name='create_post'),
    path('create_question/', views.create_question, name='create_question'),
    path('answer_question/', views.answer_question, name='answer_question'),
    path('delete-post/<int:post_id>/', views.DeletePost, name='delete_post'),
    path('like-post/<int:post_id>/', views.like_post, name='like_post'),
    path('like-article/<int:article_id>/', views.like_article, name='like_article'),
    path('like-post-comment/<int:post_comment_id>/', views.like_post_comment, name='like_post_comment'),
    path('like-answer-comment/<int:answer_comment_id>/', views.like_answer_comment, name='like_answer_comment'),
    path('like-article-comment/<int:article_comment_id>/', views.like_article_comment, name='like_article_comment'),
    path('like-book-review/<int:book_review_id>/', views.like_book_review, name='like_book_review'),
    path('admire-post/<int:post_id>/', views.admire_post, name='admire_post'),
    path('hide-post/<int:post_id>/', views.hide_post, name='hide_post'),
    path('admire-answer/<int:answer_id>/', views.admire_answer, name='admire_answer'),
    path('hide-answer/<int:answer_id>/', views.hide_answer, name='hide_answer'),
    path('delete-answer/<int:answer_id>/', views.DeleteAnswer, name='delete_answer'),
    path('hide-question/<int:question_id>/', views.hide_question, name='hide_question'),
    path('delete-question/<int:question_id>/', views.DeleteQuestion, name='delete_question'),
    path('delete-post-comment/<int:post_comment_id>/', views.delete_post_comment, name='delete_post_comment'),
    path('delete-answer-comment/<int:answer_comment_id>/', views.delete_answer_comment, name='delete_answer_comment'),
    path('delete-article-comment/<int:article_comment_id>/', views.delete_article_comment, name='delete_article_comment'),
    path('delete-book-review/<int:book_review_id>/', views.delete_book_review, name='delete_book_review'),
]