# Generated by Django 4.2.2 on 2023-07-03 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="frequency",
        ),
    ]
