# Generated by Django 4.2.2 on 2023-06-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="identifier",
            field=models.CharField(default="malaica", max_length=100),
        ),
    ]
