# Generated by Django 4.2.2 on 2023-07-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_homepage_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
                ("username", models.CharField(max_length=100)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        default="images/default.jpg",
                        null=True,
                        upload_to="Testimonials",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
