# Generated by Django 4.2.2 on 2023-07-29 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blocked",
            field=models.ManyToManyField(
                blank=True, related_name="profile_blocked", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="profile_follower", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
