# Generated by Django 4.2.2 on 2023-08-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_profile_blocked_alter_profile_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="pro_image",
            field=models.ImageField(blank=True, null=True, upload_to="ProfileImages/"),
        ),
    ]
