# Generated by Django 4.2.2 on 2023-08-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0007_alter_articlelike_unique_together_and_more"),
        ("home", "0007_remove_profile_first_name_remove_profile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="posts_blacklist",
            field=models.ManyToManyField(
                blank=True, related_name="profile_posts_blacklist", to="components.post"
            ),
        ),
    ]
