# Generated by Django 4.2.2 on 2023-08-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0007_answer_admirers"),
        ("home", "0008_profile_posts_blacklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="answers_blacklist",
            field=models.ManyToManyField(
                blank=True, related_name="profile_answers_blacklist", to="forum.answer"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="questions_blacklist",
            field=models.ManyToManyField(
                blank=True,
                related_name="profile_questions_blacklist",
                to="forum.question",
            ),
        ),
    ]
