# Generated by Django 4.2.2 on 2023-07-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
