# Generated by Django 4.2.2 on 2023-07-28 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("components", "0004_alter_book_image_alter_book_new_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="admirers",
            field=models.ManyToManyField(
                blank=True, related_name="post_admirer", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
