# Generated by Django 4.2.2 on 2023-08-05 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("components", "0005_post_admirers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="admirers",
            field=models.ManyToManyField(
                blank=True, related_name="post_admirers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.DeleteModel(
            name="PostLike",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
