# Generated by Django 4.2.2 on 2023-08-13 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0008_rename_user_articlereadingactivity_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlereadingactivity",
            old_name="author",
            new_name="user",
        ),
    ]
