# Generated by Django 4.2.2 on 2023-09-02 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0013_alter_book_contributer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlecomment",
            old_name="author",
            new_name="contributer",
        ),
    ]
