# Generated by Django 4.2.2 on 2023-09-02 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0014_rename_author_articlecomment_contributer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlecomment",
            name="contributer",
        ),
    ]
