# Generated by Django 4.2.2 on 2023-09-02 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("components", "0017_rename_author_article_contributer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
